### ISSUE TITLE
Call to undefined method Nahid\JsonQ\Jsonq::groupBy()

### ISSUE THREAD

**Issue by Steven0110** [nahid/jsonq#12]
Hi, I'm using JsonQ on Laravel 5.4. I followed the steps:
1.- run $composer require nahid/jsonq
2.- Add "use "Nahid\JsonQ\Jsonq;" to controller
The next code shows that error:

_$jsonq = new Jsonq();
$json = $jsonq->json('{"users":[{"name":"Name1","email":"x@dom.com","type":"1"},{"name":"Name2","email":"y@dom.com","type":"2"}]}');
$types = $json->from('users')->groupBy('type')->get();_

I've tested other library functions, and they work fine, but it does not work when I use groupBy()

**Comment by nahid** [comment]
Please use version `v5.0.0`
