### ISSUE TITLE
query always returns 0 results for clause "where boolean key = false"

### ISSUE THREAD

**Issue by lecleach** [nahid/jsonq#30]
Hi,

Querying a boolean type key always returns empty dataset for "false" value.

On line 374 of JsonQueriable.php, maybe it could help to replace "$value ? ... : false" by "isset($value) ? ... : false".

Thanks for the great job,
J.

**Comment by nahid** [comment]
Please share your dataset and code

**Comment by lecleach** [comment]
Here is a basic dataset (no root element) :
[{"name":"foo","isArchived":true},[{"name":"bar","isArchived":false}]

When i do : 
->where('isArchived', '=', true);
... all is ok

When i do : 
->where('isArchived', '=', false);
... always 0 results

When $value is "false" ; test on line 374 returns always false.
When i change this test on line 374 to isset($value) , i have the awaited results.

**Comment by maciejkosiarski** [comment]
In development the issue does not occur.

**Comment by nahid** [comment]
@lecleach this problem was solved. you can query this way.

```php
$jsonq->from('.')->where('isArchived', '==', false)->get();
```

or 

```php
$jsonq->from('.')->whereBool('isArchived', false)->get();
```

Please update JsonQ with `v5.2.1`

**Comment by lecleach** [comment]
Thanks a lot !
