### ISSUE TITLE
We can't search the data on LIKE query

### ISSUE THREAD

**Issue by shaan24k** [nahid/jsonq#43]
How do i search the data using **LIKE** in query

**Comment by sergiuwd** [comment]
`whereStartsWith`, `whereEndsWith`, `whereContains`

**Comment by umeshgkblabs** [comment]
@nahid 
How can search for multiple columns on JSON Data?

For Example:
{
       "products": [
		{"id":1, "user_id": 2, "city": "bsl", "name":"iPhone", "cat":1, "price": 80000},
		{"id":2, "user_id": 2, "city": null, "name":"Macbook Pro", "cat": 2, "price": 150000},
		{"id":3, "user_id": 2, "city": "dhk", "name":"Redmi 3S Prime", "cat": 1, "price": 12000},
		{"id":4, "user_id": 1, "city": Redmi, "name":"Redmi 4X", "cat":1, "price": 15000},
		{"id":5, "user_id": 1, "city": "bsl", "name":"Macbook Air", "cat": 2, "price": 110000},
		{"id":6, "user_id": 2, "city": null, "name":"Macbook Air Mini", "cat": 2, "price": 105000}
	]
} 

I want to search the **name** and **city** both column search. It is possible??

I've Tried **whereContains** method but it is not working.

cc: @shaan24k  @sergiuwd  @me-shaon  @lo00l

**Comment by nahid** [comment]
Yes its possible. Try this

```php
$data = $jsonq->from('products')->where('name', '=', 'iPhone')->where('city', '=', 'bsl')->get();
```

**Comment by umeshgkblabs** [comment]
@nahid 
I want to search in multiple columns orwhereContains with multiple columns.?

In Above Example Json Data I'm trying to search **Redmi** then I want to check this string constraint on **Name** and **City** Column?.

Can you please help me with this 

Thanks
