### ISSUE TITLE
How to use a previous set as a new set to query over those results?

### ISSUE THREAD

**Issue by dimitrihilverda** [nahid/jsonq#52]
I like to use a pre queried result set to do another query over, I do not get it to work.

if I did this:
$jsonQO->Where('Position.Status', '=', $value);
$jsonQO->Where('Position.Hours', '=', $othervalue);
$jsonQO->Where(Position.Location, '=', $jetAnotherValue);
$jsonQO->from('vacancy')->get();

Now I want to do another where on the results
I tryed : 
$jsonQO = $jsonQO->from('vacancy')->get();
$jsonQO->where('Position.JobTitle', 'contains', $value);
$jsonQO->from('vacancy')->get();

but that did not work...

**Comment by nahid** [comment]
use `$jsonQO->reset()`
