### ISSUE TITLE
Beerpay link is broken

### ISSUE THREAD

**Issue by tomkeysers** [nahid/jsonq#57]
Just wanted to thank you for your awesome work with a lil donation, but Beerpay tells me your api key has expired.

**Comment by nahid** [comment]
@tomkeysers thank you for your interest. Your appreciation is really inspire me. But the bad thing is Beerpay already shutdown their service due to introducing github sponsors. And the another bad thing is I'm from Bangladesh and github does't support the region.

**Comment by tomkeysers** [comment]
@nahid Aw man that's a shame. You totally deserve it!
